Added Brazilian Portuguese Translations
hackclub/global pull request #52
Opened 2022-12-21 14:06 UTC by LuanderFarias

2022-12-21 14:06 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/copy/pt-BR**](https://around-the-globe-9q4qilgao.hackclub.dev/copy/pt-BR) |
|:-:|
|<a href="https://around-the-globe-9q4qilgao.hackclub.dev/copy/pt-BR"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/hhgG3UbCvXi1Ggt_bbb-kWCnBYJj98MwTaOg_lrL6V2OwLjzDMj5Dy6NXnoPWV6NnaTiVwTP2oxI1TkhALzrHg.png&w=600" alt="Screenshot of /copy/pt-BR" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ymxyPUSHN02D5yCJHqgjSrAbNofAK5BlPGSe_LSumaEk_M3YoXuT83Av-AZ7NEjt9Ruj6Oo0NJHraq-6q4ZnDg.png">(view full size)</a> |







Commit 877c032cf4b2130ef9e7fb7f6132af33e506683d (https://around-the-globe-9q4qilgao.hackclub.dev).

2022-12-21 16:07 UTC, NowDev requested changes
Has some brazilian portuguese typos :)

2022-12-21 16:07 UTC, NowDev commented on pages/copy/pt-BR.mdx
> +Hack Club é uma rede de clubs de ciencias da computação onde os estudantes aprendem a programar criando projetos.
```suggestion
Hack Club é uma rede de clubes de ciências da computação onde os estudantes aprendem a programar criando projetos.
```

2022-12-21 16:12 UTC, NowDev commented
Btw, the code you've used for Brazil is actually [the ISO 639-1 code for Breton](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=br),

2022-12-21 16:32 UTC, LucasHT22 commented
Eu não entendi, a página alterada seria a inicial? Se sim, tem um repositório separado, veja: https://github.com/hack-club-brasil/v1

2022-12-22 02:19 UTC, sampoder reviewed
Hey @LuanderFarias! Super appreciate the PR, however, we currently have the community maintained http://brasil.hackclub.com/ as @LucasHT22 mentioned. I'm going to close this PR to prevent duplication. Once again, thank you for the PR! Really appreciated.

2022-12-22 02:19 UTC, closed without merging